development:
  adapter: mysql2
  database: ctw_development
  host: 127.0.0.1
  username: root
  password: '1'

test:
  adapter: mysql2
  database: ctw_test
  host: 127.0.0.1
  username: root
  password: '1'

production:
  adapter: mysql2
  database: ctw_development
  host: 127.0.0.1
  username: root
  password: '1'
